name: Sync comma's LFS

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  push:
    branches:
      - 'master-new'
  pull_request:
    branches:
      - 'master-new' 
  workflow_dispatch:  # enables manual triggering
    inputs:
      upstream_branch:
        default: 'master'
        type: string
        
jobs:
  sync:
    runs-on: ubuntu-latest
    # Skip if PR is in draft mode
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false)
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: 'commaai/openpilot'
          ref: ${{ inputs.upstream_branch }}
          lfs: true
            

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add GitLab public keys
        run: |
          ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
      
      - name: Set SP LFS
        run: |
          git config lfs.pushurl="ssh://git@gitlab.com-devtekve/sunnypilot/public/sunnypilot-new-lfs.git"

      - name: Push LFS
        id: sync-and-commit
        run: |
          git lfs push --all origin