name: sunnypilot publish and notify

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["sunnypilot prebuilt action"]
    types:
      - completed

env:
  OUTPUT_DIR: ${{ github.workspace }}/output
  CI_DIR: ${{ github.workspace }}/release/ci
  PUBLIC_REPO_URL: "https://github.com/sunnypilot/sunnypilot"

jobs:
  prepare:
    runs-on: ubuntu-24.04
    if: |
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      (github.event_name == 'workflow_dispatch')
    outputs:
      should_publish: ${{ steps.get-build-outputs.outputs.should_publish }}
      new_branch: ${{ steps.get-build-outputs.outputs.new_branch }}
      version: ${{ steps.get-build-outputs.outputs.version }}
      extra_version_identifier: ${{ steps.get-build-outputs.outputs.extra_version_identifier || github.event.workflow_run.id}}
      branch_name: ${{ steps.get-build-outputs.outputs.branch_name }}
    steps:
      - name: Find latest successful build run
        if: github.event_name == 'workflow_dispatch'
        id: find-run
        uses: actions/github-script@v7
        with:
          script: |
            const branch = context.ref.replace('refs/heads/', '');
            
            // First try to find PR associated with the branch
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${branch}`,
              state: 'open'
            });
            
            let targetBranch = branch;
            if (prs.data.length > 0) {
              console.log(`Found PR from branch ${branch}`);
              targetBranch = prs.data[0].head.ref;
            }
            
            // Get workflow runs for the build workflow
            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'sunnypilot-build.yml',
              branch: targetBranch,
              status: 'success'
            });
            
            if (runs.data.workflow_runs.length === 0) {
              core.setFailed(`No successful builds found for branch ${targetBranch}`);
              return;
            }
            
            const latestRun = runs.data.workflow_runs[0];
            core.setOutput('run_id', latestRun.id);
            console.log(`Latest successful build run ID: ${latestRun.id}`);

      - name: Download workflow artifact from workflow_run
        if: github.event_name == 'workflow_run'
        uses: dawidd6/action-download-artifact@v3
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: prebuilt

      - name: Download workflow artifact from workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        uses: dawidd6/action-download-artifact@v3
        with:
          run_id: ${{ steps.find-run.outputs.run_id }}
          name: prebuilt

      - name: Get build job outputs
        id: get-build-outputs
        uses: actions/github-script@v7
        with:
          script: |
            const runId = '${{ github.event_name }}' === 'workflow_run' 
              ? context.payload.workflow_run.id
              : ${{ steps.find-run.outputs.run_id }};
            
            const run = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runId
            });
            
            const buildJob = run.data.jobs.find(j => j.name === 'build');
            for (const step of buildJob.steps) {
              if (step.name === 'Set environment variables') {
                const outputs = {};
                for (const [key, value] of Object.entries(buildJob.outputs)) {
                  core.setOutput(key, value);
                  outputs[key] = value;
                }
                console.log('Build outputs:', outputs);
                break;
              }
            }

  publish:
    needs: prepare
    runs-on: ubuntu-24.04
    if: needs.prepare.outputs.should_publish == 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Untar prebuilt
        run: |
          mkdir -p ${{ env.OUTPUT_DIR }}
          tar xzf prebuilt.tar.gz -C ${{ env.OUTPUT_DIR }}

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Publish to Public Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ${{ env.CI_DIR }}/publish.sh \
            "${{ github.workspace }}" \
            "${{ env.OUTPUT_DIR }}" \
            "${{ needs.prepare.outputs.new_branch }}" \
            "${{ needs.prepare.outputs.version }}" \
            "https://x-access-token:${{github.token}}@github.com/sunnypilot/sunnypilot.git" \
            "-${{ needs.prepare.outputs.extra_version_identifier }}"

  notify:
    needs: [prepare, publish]
    runs-on: ubuntu-24.04
    if: always() && needs.prepare.result == 'success'
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq gettext-base

      - name: Check notification branch
        id: check-branch
        run: |
          # Get branch name from prepare job
          export branch_name="${{ needs.prepare.outputs.branch_name }}"
          echo "🔍 Current branch: $branch_name"

          echo "📋 Checking against dev-feedback notification branches list..."
          echo "Current notifiable branches: ${{ vars.DEV_FEEDBACK_NOTIFICATION_BRANCHES }}"
          echo ""

          IFS=',' read -ra BRANCHES <<< "${{ vars.DEV_FEEDBACK_NOTIFICATION_BRANCHES }}"
          for branch in "${BRANCHES[@]}"; do
            if [ "$branch_name" = "$branch" ]; then 
              echo "✅ Match found! '$branch_name' will notify to dev-feedback channel"
              echo "is_dev_feedback_notifiable_branch=true" >> $GITHUB_OUTPUT
              break
            fi
          done

          echo ""
          echo "----   ℹ️ To update the list of branches that notify to dev-feedback   -----"
          echo ""
          echo "1. Go to: ${{ github.server_url }}/${{ github.repository }}/settings/variables/actions/DEV_FEEDBACK_NOTIFICATION_BRANCHES"
          echo "2. Current value: [${{ vars.DEV_FEEDBACK_NOTIFICATION_BRANCHES }}]"
          echo "3. Update as needed (comma-separated list with no spaces)"

      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ steps.check-branch.outputs.is_dev_feedback_notifiable_branch == 'true' && needs.publish.result != 'skipped' && secrets.DISCORD_DEV_FEEDBACK_CHANNEL_WEBHOOK || secrets.DISCORD_DEV_PRIVATE_CHANNEL_WEBHOOK }}
        run: |
          TEMPLATE='${{ needs.publish.result == 'skipped' && vars.DISCORD_INTERNAL_WORKFLOW_ALERT || vars.DISCORD_GENERAL_UPDATE_NOTICE }}'
          export VERSION="${{ needs.prepare.outputs.version }}"
          export branch_name="${{ needs.prepare.outputs.branch_name }}"
          export new_branch="${{ needs.prepare.outputs.new_branch }}"
          export extra_version_identifier="${{ needs.prepare.outputs.extra_version_identifier }}"
          echo ${TEMPLATE} | envsubst | jq -c '.' | tee payload.json
#          curl -X POST -H "Content-Type: application/json" -d @payload.json $DISCORD_WEBHOOK