name: sync-fork
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch: { }
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: gh repo sync nayan8teen/openpilot -b dev-c3-new --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
